housedata<-read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings = "?")
combine<-subset(housedata, housedata$Date=="1/2/2007"|housedata$Date=="2/2/2007")
combine$Date <- as.Date(combine$Date, format="%d/%m/%Y")
combine$Time <- strptime(combine$Time, format="%H:%M:%S")
combine[1:1440,"Time"] <- format(combine[1:1440,"Time"],"2007-02-01 %H:%M:%S")
combine[1441:2880,"Time"] <- format(combine[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(combine$Time, combine$Sub_metering_1,main = "Energy Sub metering", type="n", xlab="", ylab = "Energy Sub metering")
with(combine, lines(Time, as.numeric(as.character(Sub_metering_1))))
with(combine, lines(Time, as.numeric(as.character(Sub_metering_2)), col="red"))
with(combine, lines(Time, as.numeric(as.character(Sub_metering_3)), col="blue"))
legend("topright", lty = 1, col=c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

